### ISSUE TITLE
Doesn't build under latest 2.4 - retarget to .NET 4.6.1

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Website#313]
### Steps to reproduce
1. Build using Starcounter `2.4.0.4692`

### Error
New Starcounter targets .NET Framework 4.6.1. It can't be used as a dependency for website which targets 4.5
```warning MSB3274: The primary reference "Starcounter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".```
```error CS0246: The type or namespace name 'Starcounter' could not be found (are you missing a using directive or an assembly reference?)```

### Proposed solution

Retarget to 4.6.1

**Comment by warpech** [comment]
@kegor could you pls do that on a feature branch from `master-2.4`?

**Comment by kegor** [comment]
Changes where merged into `master-2.4` in #314.
Can this issue be closed?

**Comment by warpech** [comment]
I think yes, thanks!
